### PR TITLE
FIX: EbayInfotip focus host on closing infotip

### LINKED ISSUE #67: Accessibility: Infotip focus on collapse
After collapsing an infotip the focus get lost in the page but it should focus the host element

### PR DESCRIPTION
**Pull request by HenriqueLimas**
- Add a `hostRef` on `useTooltip` and focus on it on collapse

Fix #67

### CODE REVIEW

File: src/common/tooltip-utils/use-tooltip.ts [hunk 1]
```diff
@@ -26,6 +27,10 @@ export const useTooltip = ({ onExpand, onCollapse, initialExpanded = false }: Us
         if (onCollapse) {
             onCollapse()
         }
+
+        if (hostRef?.current) {
+            hostRef.current.focus()
+        }
```
Comment (abiyasa) [inline src/common/tooltip-utils/use-tooltip.ts:33]:
```suggestion
        hostRef?.current?.focus()
```

**Review by abiyasa — APPROVED** [review]
LGTM 👍

File: src/common/tooltip-utils/use-tooltip.ts (hunk 1 above)
Comment (HenriqueLimas) [reply src/common/tooltip-utils/use-tooltip.ts]: Thanks, updated. eslint used to fail in the past, considering it as a ternary, it seems it got fixed 👍
